version: "3.9"
services:
  init-db:
    build:
      context: .
      dockerfile: ./web/Dockerfile
    env_file: .env
    command: ["python", "-m", "app.init_db_script"]
    restart: "no"

  web:
    build:
      context: .
      dockerfile: ./web/Dockerfile
    env_file: .env
    depends_on:
      init-db:
        condition: service_completed_successfully
    ports:
      - "8000:8000"
    command: ["gunicorn", "app:create_app()", "-b", "0.0.0.0:8000", "-w", "2", "-k", "gthread", "--threads", "4"]

  worker:
    build:
      context: .
      dockerfile: ./web/Dockerfile
    env_file: .env
    depends_on:
      init-db:
        condition: service_completed_successfully
    command: ["celery", "-A", "app.celery_app.celery", "worker", "--loglevel=INFO"]

  beat:
    build:
      context: .
      dockerfile: ./web/Dockerfile
    env_file: .env
    depends_on:
      worker:
        condition: service_started
    command: ["celery", "-A", "app.celery_app.celery", "beat", "--loglevel=INFO"]

